title: 1UPNOTE
description: "UI/UX blog for advanced web designers"
email: 1up@1upz.com
baseurl: ""
url: http://1upnote.com
markdown: kramdown
permalink: /:title
timezone: "Asia/Seoul"
language: ko
author:
  name: 1UP
  email: 1up@1upz.com
  twitter: https://twitter.com/1upz
  github: https://github.com/woneob
version: 0.0.1

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME

gems:
  - jekyll-sitemap

highlighter: pygments

sass:
  sass_dir: assets/styles/_scss
  style: compressed

compress_html:
  clippings: all
