# Website settings
title: 1upnote
tagline: Web design, development and UX
description: >-
  1upnote is a blog that focuses on standards-based design techniques,
  useful UX information and expert tips for building effective user interfaces.
baseurl: ''
url: https://1upnote.com
permalink: /:title
timezone: Asia/Seoul
version: 0.0.1

# Language and locale settings
language:
  code: ko
  locale: ko_KR
  name: Korean

# Author information
author:
  name: 1UP
  location: Seoul, Korea
  email: 1up@1upz.com
  twitter: 1upz
  github: woneob

# File pathes
path:
  css: /assets/styles
  js: /assets/scripts
  img: /assets/images

# Exclude files from the production build
exclude:
- README.md
- Gemfile
- Gemfile.lock
- CNAME
- LICENSE

# Markdown settings
markdown: kramdown

# Code highlighter settings
highlighter: pygments

# Sass settings
# http://sass-lang.com/
# http://jekyllrb.com/docs/assets/#sassscss
sass:
  add_charset: true
  sass_dir: assets/styles/_scss
  style: compressed

# Compress HTML
# https://github.com/penibelst/jekyll-compress-html
compress_html:
  clippings: all
  comments:
  - "<!-- "
  - " -->"
