# pages
-
  file: /index
  permalink: /
  date: '2017-02-30T14:00+09:00'

-
  file: /404
  type: error
  permalink: /404.html
  title: Page Not Found
  description: Page not found
  date: '2017-03-04T14:04+09:00'
  search: false

# posts
-
  file: /hello-world
  type: post
  title: Hello World
  description: test page
  summary: test page
  date: '2017-02-22T14:00+09:00'
  tags:
    - test
    - JavaScript
    - hello-world
  plugins:
    - somePlugin/plugin.js
